# Generated by Django 5.2 on 2025-04-19 09:54

import django.core.validators
import rewards.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Количество монет')),
                ('given_at', models.DateTimeField(verbose_name='Награда зачислена в')),
            ],
            options={
                'verbose_name': 'Лог награды',
                'verbose_name_plural': 'Логи наград',
            },
        ),
        migrations.CreateModel(
            name='SheduledReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество монет')),
                ('execute_at', models.DateTimeField(validators=[rewards.validators.validate_execute_date], verbose_name='Запланированное время выполнения')),
            ],
            options={
                'verbose_name': 'Запланированная награда',
                'verbose_name_plural': 'Запланированные награды',
            },
        ),
    ]
